# -*- coding: utf-8 -*-
"""data_analysis01.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZKmbMiJ6zn6bRpeDn294Q7_LBoDtY5f
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df = pd.read_csv('data.csv.xls')

df.head()

df.info()

int_columns = df.select_dtypes(include=['int64']).columns

df[int_columns] = df[int_columns].astype('object')

df.dtypes

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

df.duplicated()

numerical_df = df.select_dtypes(include=[np.number])
correlation_matrix = numerical_df.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.show()

df.hist(bins=20, figsize=(15, 10), color='blue')
plt.suptitle('Histograms of Numerical Features')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=df.select_dtypes(include=[np.number]))
plt.title('Boxplot for Numerical Features')
plt.show()

for column in df.select_dtypes(include=['object']):
    plt.figure(figsize=(10, 5))
    sns.countplot(x=column, data=df, palette='viridis')
    plt.title(f'Countplot of {column}')
    plt.xticks(rotation=45)
    plt.show()

if len(df.select_dtypes(include=[np.number]).columns) >= 2:
    num_cols = df.select_dtypes(include=[np.number]).columns[:2]
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=num_cols[0], y=num_cols[1], data=df, hue=df.select_dtypes(include=['object']).columns[0])
    plt.title(f'Scatterplot: {num_cols[0]} vs {num_cols[1]}')
    plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x=df.select_dtypes(include=['object']).columns[0], y=df.select_dtypes(include=[np.number]).columns[0], data=df)
plt.title('Barplot of Categorical vs Numerical Feature')
plt.xticks(rotation=45)
plt.show()

sns.pairplot(df.select_dtypes(include=[np.number]))
plt.suptitle('Pairplot of Numerical Features', y=1.02)
plt.show()

for col in df.select_dtypes(include=['object']):
    plt.figure(figsize=(10, 5))
    sns.boxplot(x=col, y=df.select_dtypes(include=[np.number]).columns[0], data=df, palette='Set3')
    plt.title(f'Boxplot of {col} vs Numerical Feature')
    plt.xticks(rotation=45)
    plt.show()

plt.savefig('visualization_output.png')

df.to_csv('cleaned_dataset.csv', index=False)

df.read









